# config/application.yml
defaults: &defaults
  multiforecast:
    mapping:
      '': 'http://localhost:5125'
  tagcloud:
    limit: 400

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

