# config/application.yml
defaults: &defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://localhost:5125'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

