# config/application.yml
defaults: &defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://10.33.49.163:5125'

development:
  <<: *defaults

test:
  <<: *defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://localhost:5125'

production:
  <<: *defaults

