# config/application.yml
defaults: &defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://10.33.49.163:5125'
  graph:
    tree:
      depth: 1
    single_graph:
      width: 640
      height: 396

development:
  <<: *defaults

test:
  <<: *defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://localhost:5125'

production:
  <<: *defaults

