# config/application.yml
defaults: &defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://10.33.49.163:5125'
  tree:
    depth: null
  autocomplete:
    limit: 10
  graph:
    single_graph:
      width: 640
      height: 396
    date_period_presets:
      -
        name: 'hour(1min)'
        short_name: 'sh'
      -
        name: '8hours(1min)'
        short_name: 's8h'
      -
        name: '3days(1min)'
        short_name: 's3d'
      -
        name: 'hour'
        short_name: 'h'
      -
        name: 'halfday'
        short_name: 'n'
      -
        name: 'day'
        short_name: 'd'
        active_default: true
      -
        name: 'week'
        short_name: 'w'
      -
        name: 'month'
        short_name: 'm'
      -
        name: 'year'
        short_name: 'y'

development:
  <<: *defaults

test:
  <<: *defaults
  growthforecasts:
    -
      dir: ''
      gfuri: 'http://localhost:5125'

production:
  <<: *defaults

