defaults: &defaults
  multiforecast:
    mapping:
      '': 'http://localhost:5125'
  unicorn:
    port: 4804
  tagcloud:
    limit: 400
  accordion:
    initial_depth: 1
    link_to_tree_graph: true # if false, link sections to only list_graph, no link_to tree_graph

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

