defaults: &defaults
  multiforecast:
    mapping:
      '': 'http://localhost:5125'
  unicorn:
    port: 4804
  tagcloud:
    limit: 400
  proxy: true

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

