# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#   Ensure the SQLite version 3.6.16 or later is installed
defaults: &defaults
  adapter: sqlite3
  database: db/sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *defaults

development:
  <<: *defaults
  database: db/development.sqlite3

test:
  <<: *defaults
  database: db/test.sqlite3
