date_period_terms:
  -
    name: 'hour'
    short_name: 'h'
  -
    name: '8hours'
    short_name: '8h'
  -
    name: 'halfday'
    short_name: 'n'
  -
    name: 'day'
    short_name: 'd'
  -
    name: '3days'
    short_name: '3d'
  -
    name: 'week'
    short_name: 'w'
  -
    name: 'month'
    short_name: 'm'
  -
    name: 'year'
    short_name: 'y'
sizes:
  thumbnail:
    width: 306
    height: 90
  M:
    width: 462
    height: 200
  L: 
    width: 640
    height: 277
  LL:
    width: 800
    height: 346

