# config/serverengine.yml
defaults: &defaults
  # worker options
  interval: 1
  module_name: 'Worker'
  # serverengine options
  log: 'log/serverengine.log'
  pid_path: 'log/serverengine.pid'
  log_stdout: false # Serverengine captures stdout and outputs to log file as default. Disable it
  log_stderr: false # Serverengine captures stderr and outputs to log file as default. Disable it

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  interval: 60

