# config/worker.yml
defaults: &defaults
  log: 'log/worker.log'
  pid_path: 'log/worker.pid'
  interval: 1
  log_stdout: false
  log_stderr: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
